language: python

python:
    - "3.6"

cache:
    pip:
    directories:
        - $TRAVIS_BUILD_DIR/.eggs
        - $TRAVIS_BUILD_DIR/.cache
        - $HOME/virtualenv

script:
    - pip install coveralls
    - python setup.py test
    - coveralls
